// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/device.dart';
import 'api/init.dart';
import 'api/pair.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'sysinfo_view.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppSnapshot dco_decode_app_snapshot(dynamic raw);

  @protected
  AutostartInfo dco_decode_autostart_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PendingPairingInfo dco_decode_box_autoadd_pending_pairing_info(dynamic raw);

  @protected
  DiscoveredDeviceInfo dco_decode_discovered_device_info(dynamic raw);

  @protected
  DiscoverySnapshot dco_decode_discovery_snapshot(dynamic raw);

  @protected
  ElevationSnapshot dco_decode_elevation_snapshot(dynamic raw);

  @protected
  FirewallSnapshot dco_decode_firewall_snapshot(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DiscoveredDeviceInfo> dco_decode_list_discovered_device_info(
    dynamic raw,
  );

  @protected
  List<PeerStatusInfo> dco_decode_list_peer_status_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PendingPairingInfo? dco_decode_opt_box_autoadd_pending_pairing_info(
    dynamic raw,
  );

  @protected
  PairOutcomeInfo dco_decode_pair_outcome_info(dynamic raw);

  @protected
  PeerStatusInfo dco_decode_peer_status_info(dynamic raw);

  @protected
  PendingPairingInfo dco_decode_pending_pairing_info(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  ServerSnapshot dco_decode_server_snapshot(dynamic raw);

  @protected
  SystemSnapshot dco_decode_system_snapshot(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppSnapshot sse_decode_app_snapshot(SseDeserializer deserializer);

  @protected
  AutostartInfo sse_decode_autostart_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PendingPairingInfo sse_decode_box_autoadd_pending_pairing_info(
    SseDeserializer deserializer,
  );

  @protected
  DiscoveredDeviceInfo sse_decode_discovered_device_info(
    SseDeserializer deserializer,
  );

  @protected
  DiscoverySnapshot sse_decode_discovery_snapshot(SseDeserializer deserializer);

  @protected
  ElevationSnapshot sse_decode_elevation_snapshot(SseDeserializer deserializer);

  @protected
  FirewallSnapshot sse_decode_firewall_snapshot(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DiscoveredDeviceInfo> sse_decode_list_discovered_device_info(
    SseDeserializer deserializer,
  );

  @protected
  List<PeerStatusInfo> sse_decode_list_peer_status_info(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PendingPairingInfo? sse_decode_opt_box_autoadd_pending_pairing_info(
    SseDeserializer deserializer,
  );

  @protected
  PairOutcomeInfo sse_decode_pair_outcome_info(SseDeserializer deserializer);

  @protected
  PeerStatusInfo sse_decode_peer_status_info(SseDeserializer deserializer);

  @protected
  PendingPairingInfo sse_decode_pending_pairing_info(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  ServerSnapshot sse_decode_server_snapshot(SseDeserializer deserializer);

  @protected
  SystemSnapshot sse_decode_system_snapshot(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_snapshot(AppSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_autostart_info(AutostartInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_pending_pairing_info(
    PendingPairingInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_discovered_device_info(
    DiscoveredDeviceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_discovery_snapshot(
    DiscoverySnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_elevation_snapshot(
    ElevationSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_firewall_snapshot(
    FirewallSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_discovered_device_info(
    List<DiscoveredDeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_peer_status_info(
    List<PeerStatusInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_pending_pairing_info(
    PendingPairingInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pair_outcome_info(
    PairOutcomeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_status_info(
    PeerStatusInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pending_pairing_info(
    PendingPairingInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_server_snapshot(
    ServerSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_system_snapshot(
    SystemSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
