// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/device.dart';
import 'api/init.dart';
import 'api/pair.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'sysinfo_view.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 843897259;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'agent_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AppSnapshot> crateApiInitAppInit();

  Future<AutostartInfo> crateApiInitAutostartStatus();

  Future<List<DiscoveredDeviceInfo>> crateApiPairDiscoveredDevices();

  Future<void> crateApiInitApp();

  Future<PendingPairingInfo?> crateApiPairPairingPending();

  Future<List<PeerStatusInfo>> crateApiPairPeersStatus();

  Future<SystemSnapshot> crateApiInitRefreshSystem();

  Future<PairOutcomeInfo> crateApiPairRequestPairing({required String uuid});

  Future<void> crateApiPairRespondPairing({required bool approve});

  Future<String?> crateApiInitSelectShareAddress({
    required List<(String, String)> candidates,
  });

  Future<AutostartInfo> crateApiInitSetAutostart({required bool enabled});

  Future<AppSnapshot> crateApiDeviceSetShortName({String? name});

  Future<String> crateApiInitSharePayload();

  Future<bool> crateApiInitTrayHostAvailable();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AppSnapshot> crateApiInitAppInit() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInitAppInitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppInitConstMeta =>
      const TaskConstMeta(debugName: "app_init", argNames: []);

  @override
  Future<AutostartInfo> crateApiInitAutostartStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_autostart_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInitAutostartStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAutostartStatusConstMeta =>
      const TaskConstMeta(debugName: "autostart_status", argNames: []);

  @override
  Future<List<DiscoveredDeviceInfo>> crateApiPairDiscoveredDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_discovered_device_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPairDiscoveredDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairDiscoveredDevicesConstMeta =>
      const TaskConstMeta(debugName: "discovered_devices", argNames: []);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<PendingPairingInfo?> crateApiPairPairingPending() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_pending_pairing_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPairPairingPendingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairPairingPendingConstMeta =>
      const TaskConstMeta(debugName: "pairing_pending", argNames: []);

  @override
  Future<List<PeerStatusInfo>> crateApiPairPeersStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_peer_status_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPairPeersStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairPeersStatusConstMeta =>
      const TaskConstMeta(debugName: "peers_status", argNames: []);

  @override
  Future<SystemSnapshot> crateApiInitRefreshSystem() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_system_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInitRefreshSystemConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitRefreshSystemConstMeta =>
      const TaskConstMeta(debugName: "refresh_system", argNames: []);

  @override
  Future<PairOutcomeInfo> crateApiPairRequestPairing({required String uuid}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uuid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pair_outcome_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPairRequestPairingConstMeta,
        argValues: [uuid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairRequestPairingConstMeta =>
      const TaskConstMeta(debugName: "request_pairing", argNames: ["uuid"]);

  @override
  Future<void> crateApiPairRespondPairing({required bool approve}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(approve, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPairRespondPairingConstMeta,
        argValues: [approve],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairRespondPairingConstMeta =>
      const TaskConstMeta(debugName: "respond_pairing", argNames: ["approve"]);

  @override
  Future<String?> crateApiInitSelectShareAddress({
    required List<(String, String)> candidates,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_record_string_string(candidates, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitSelectShareAddressConstMeta,
        argValues: [candidates],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitSelectShareAddressConstMeta =>
      const TaskConstMeta(
        debugName: "select_share_address",
        argNames: ["candidates"],
      );

  @override
  Future<AutostartInfo> crateApiInitSetAutostart({required bool enabled}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_autostart_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInitSetAutostartConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitSetAutostartConstMeta =>
      const TaskConstMeta(debugName: "set_autostart", argNames: ["enabled"]);

  @override
  Future<AppSnapshot> crateApiDeviceSetShortName({String? name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDeviceSetShortNameConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceSetShortNameConstMeta =>
      const TaskConstMeta(debugName: "set_short_name", argNames: ["name"]);

  @override
  Future<String> crateApiInitSharePayload() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInitSharePayloadConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitSharePayloadConstMeta =>
      const TaskConstMeta(debugName: "share_payload", argNames: []);

  @override
  Future<bool> crateApiInitTrayHostAvailable() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitTrayHostAvailableConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitTrayHostAvailableConstMeta =>
      const TaskConstMeta(debugName: "tray_host_available", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppSnapshot dco_decode_app_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return AppSnapshot(
      version: dco_decode_String(arr[0]),
      uuid: dco_decode_String(arr[1]),
      shortName: dco_decode_opt_String(arr[2]),
      notice: dco_decode_opt_String(arr[3]),
      system: dco_decode_system_snapshot(arr[4]),
      server: dco_decode_server_snapshot(arr[5]),
      elevation: dco_decode_elevation_snapshot(arr[6]),
      firewall: dco_decode_firewall_snapshot(arr[7]),
      discovery: dco_decode_discovery_snapshot(arr[8]),
    );
  }

  @protected
  AutostartInfo dco_decode_autostart_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AutostartInfo(
      enabled: dco_decode_bool(arr[0]),
      mechanism: dco_decode_String(arr[1]),
      detail: dco_decode_String(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PendingPairingInfo dco_decode_box_autoadd_pending_pairing_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pending_pairing_info(raw);
  }

  @protected
  DiscoveredDeviceInfo dco_decode_discovered_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return DiscoveredDeviceInfo(
      uuid: dco_decode_String(arr[0]),
      shortName: dco_decode_opt_String(arr[1]),
      hostname: dco_decode_String(arr[2]),
      port: dco_decode_u_16(arr[3]),
      sourceIp: dco_decode_String(arr[4]),
      paired: dco_decode_bool(arr[5]),
      conflicted: dco_decode_bool(arr[6]),
    );
  }

  @protected
  DiscoverySnapshot dco_decode_discovery_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DiscoverySnapshot(
      available: dco_decode_bool(arr[0]),
      detail: dco_decode_String(arr[1]),
    );
  }

  @protected
  ElevationSnapshot dco_decode_elevation_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ElevationSnapshot(
      admin: dco_decode_bool(arr[0]),
      detail: dco_decode_String(arr[1]),
    );
  }

  @protected
  FirewallSnapshot dco_decode_firewall_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FirewallSnapshot(
      manager: dco_decode_opt_String(arr[0]),
      active: dco_decode_bool(arr[1]),
      applied: dco_decode_bool(arr[2]),
      detail: dco_decode_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DiscoveredDeviceInfo> dco_decode_list_discovered_device_info(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_discovered_device_info)
        .toList();
  }

  @protected
  List<PeerStatusInfo> dco_decode_list_peer_status_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_peer_status_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PendingPairingInfo? dco_decode_opt_box_autoadd_pending_pairing_info(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_pending_pairing_info(raw);
  }

  @protected
  PairOutcomeInfo dco_decode_pair_outcome_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PairOutcomeInfo(
      status: dco_decode_String(arr[0]),
      detail: dco_decode_String(arr[1]),
    );
  }

  @protected
  PeerStatusInfo dco_decode_peer_status_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return PeerStatusInfo(
      uuid: dco_decode_String(arr[0]),
      shortName: dco_decode_opt_String(arr[1]),
      address: dco_decode_String(arr[2]),
      port: dco_decode_u_16(arr[3]),
      status: dco_decode_String(arr[4]),
      note: dco_decode_String(arr[5]),
      conflicted: dco_decode_bool(arr[6]),
    );
  }

  @protected
  PendingPairingInfo dco_decode_pending_pairing_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PendingPairingInfo(
      id: dco_decode_u_64(arr[0]),
      uuid: dco_decode_String(arr[1]),
      shortName: dco_decode_opt_String(arr[2]),
      port: dco_decode_u_16(arr[3]),
      sourceIp: dco_decode_String(arr[4]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  ServerSnapshot dco_decode_server_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ServerSnapshot(
      running: dco_decode_bool(arr[0]),
      port: dco_decode_u_16(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  SystemSnapshot dco_decode_system_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SystemSnapshot(
      platform: dco_decode_String(arr[0]),
      locale: dco_decode_String(arr[1]),
      localTime: dco_decode_String(arr[2]),
      cpu: dco_decode_String(arr[3]),
      memory: dco_decode_String(arr[4]),
      ipAddresses: dco_decode_list_String(arr[5]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppSnapshot sse_decode_app_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_String(deserializer);
    var var_uuid = sse_decode_String(deserializer);
    var var_shortName = sse_decode_opt_String(deserializer);
    var var_notice = sse_decode_opt_String(deserializer);
    var var_system = sse_decode_system_snapshot(deserializer);
    var var_server = sse_decode_server_snapshot(deserializer);
    var var_elevation = sse_decode_elevation_snapshot(deserializer);
    var var_firewall = sse_decode_firewall_snapshot(deserializer);
    var var_discovery = sse_decode_discovery_snapshot(deserializer);
    return AppSnapshot(
      version: var_version,
      uuid: var_uuid,
      shortName: var_shortName,
      notice: var_notice,
      system: var_system,
      server: var_server,
      elevation: var_elevation,
      firewall: var_firewall,
      discovery: var_discovery,
    );
  }

  @protected
  AutostartInfo sse_decode_autostart_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_mechanism = sse_decode_String(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return AutostartInfo(
      enabled: var_enabled,
      mechanism: var_mechanism,
      detail: var_detail,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PendingPairingInfo sse_decode_box_autoadd_pending_pairing_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pending_pairing_info(deserializer));
  }

  @protected
  DiscoveredDeviceInfo sse_decode_discovered_device_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uuid = sse_decode_String(deserializer);
    var var_shortName = sse_decode_opt_String(deserializer);
    var var_hostname = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_sourceIp = sse_decode_String(deserializer);
    var var_paired = sse_decode_bool(deserializer);
    var var_conflicted = sse_decode_bool(deserializer);
    return DiscoveredDeviceInfo(
      uuid: var_uuid,
      shortName: var_shortName,
      hostname: var_hostname,
      port: var_port,
      sourceIp: var_sourceIp,
      paired: var_paired,
      conflicted: var_conflicted,
    );
  }

  @protected
  DiscoverySnapshot sse_decode_discovery_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_available = sse_decode_bool(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return DiscoverySnapshot(available: var_available, detail: var_detail);
  }

  @protected
  ElevationSnapshot sse_decode_elevation_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_admin = sse_decode_bool(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return ElevationSnapshot(admin: var_admin, detail: var_detail);
  }

  @protected
  FirewallSnapshot sse_decode_firewall_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_manager = sse_decode_opt_String(deserializer);
    var var_active = sse_decode_bool(deserializer);
    var var_applied = sse_decode_bool(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return FirewallSnapshot(
      manager: var_manager,
      active: var_active,
      applied: var_applied,
      detail: var_detail,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DiscoveredDeviceInfo> sse_decode_list_discovered_device_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DiscoveredDeviceInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_discovered_device_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<PeerStatusInfo> sse_decode_list_peer_status_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PeerStatusInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_peer_status_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PendingPairingInfo? sse_decode_opt_box_autoadd_pending_pairing_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_pending_pairing_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PairOutcomeInfo sse_decode_pair_outcome_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_String(deserializer);
    var var_detail = sse_decode_String(deserializer);
    return PairOutcomeInfo(status: var_status, detail: var_detail);
  }

  @protected
  PeerStatusInfo sse_decode_peer_status_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uuid = sse_decode_String(deserializer);
    var var_shortName = sse_decode_opt_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_note = sse_decode_String(deserializer);
    var var_conflicted = sse_decode_bool(deserializer);
    return PeerStatusInfo(
      uuid: var_uuid,
      shortName: var_shortName,
      address: var_address,
      port: var_port,
      status: var_status,
      note: var_note,
      conflicted: var_conflicted,
    );
  }

  @protected
  PendingPairingInfo sse_decode_pending_pairing_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_64(deserializer);
    var var_uuid = sse_decode_String(deserializer);
    var var_shortName = sse_decode_opt_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_sourceIp = sse_decode_String(deserializer);
    return PendingPairingInfo(
      id: var_id,
      uuid: var_uuid,
      shortName: var_shortName,
      port: var_port,
      sourceIp: var_sourceIp,
    );
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  ServerSnapshot sse_decode_server_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_running = sse_decode_bool(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ServerSnapshot(
      running: var_running,
      port: var_port,
      error: var_error,
    );
  }

  @protected
  SystemSnapshot sse_decode_system_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_platform = sse_decode_String(deserializer);
    var var_locale = sse_decode_String(deserializer);
    var var_localTime = sse_decode_String(deserializer);
    var var_cpu = sse_decode_String(deserializer);
    var var_memory = sse_decode_String(deserializer);
    var var_ipAddresses = sse_decode_list_String(deserializer);
    return SystemSnapshot(
      platform: var_platform,
      locale: var_locale,
      localTime: var_localTime,
      cpu: var_cpu,
      memory: var_memory,
      ipAddresses: var_ipAddresses,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_snapshot(AppSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.uuid, serializer);
    sse_encode_opt_String(self.shortName, serializer);
    sse_encode_opt_String(self.notice, serializer);
    sse_encode_system_snapshot(self.system, serializer);
    sse_encode_server_snapshot(self.server, serializer);
    sse_encode_elevation_snapshot(self.elevation, serializer);
    sse_encode_firewall_snapshot(self.firewall, serializer);
    sse_encode_discovery_snapshot(self.discovery, serializer);
  }

  @protected
  void sse_encode_autostart_info(AutostartInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_String(self.mechanism, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_pending_pairing_info(
    PendingPairingInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pending_pairing_info(self, serializer);
  }

  @protected
  void sse_encode_discovered_device_info(
    DiscoveredDeviceInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uuid, serializer);
    sse_encode_opt_String(self.shortName, serializer);
    sse_encode_String(self.hostname, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.sourceIp, serializer);
    sse_encode_bool(self.paired, serializer);
    sse_encode_bool(self.conflicted, serializer);
  }

  @protected
  void sse_encode_discovery_snapshot(
    DiscoverySnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.available, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_elevation_snapshot(
    ElevationSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.admin, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_firewall_snapshot(
    FirewallSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.manager, serializer);
    sse_encode_bool(self.active, serializer);
    sse_encode_bool(self.applied, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_discovered_device_info(
    List<DiscoveredDeviceInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_discovered_device_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_peer_status_info(
    List<PeerStatusInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_peer_status_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_pending_pairing_info(
    PendingPairingInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_pending_pairing_info(self, serializer);
    }
  }

  @protected
  void sse_encode_pair_outcome_info(
    PairOutcomeInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.status, serializer);
    sse_encode_String(self.detail, serializer);
  }

  @protected
  void sse_encode_peer_status_info(
    PeerStatusInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uuid, serializer);
    sse_encode_opt_String(self.shortName, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_String(self.note, serializer);
    sse_encode_bool(self.conflicted, serializer);
  }

  @protected
  void sse_encode_pending_pairing_info(
    PendingPairingInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.id, serializer);
    sse_encode_String(self.uuid, serializer);
    sse_encode_opt_String(self.shortName, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.sourceIp, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_server_snapshot(
    ServerSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.running, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_system_snapshot(
    SystemSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.platform, serializer);
    sse_encode_String(self.locale, serializer);
    sse_encode_String(self.localTime, serializer);
    sse_encode_String(self.cpu, serializer);
    sse_encode_String(self.memory, serializer);
    sse_encode_list_String(self.ipAddresses, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
