// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 面板所需的系统信息快照（全部为面向展示的字符串，取值来自当前系统实际状态）。
class SystemSnapshot {
  /// 操作系统名称与版本（如 `Ubuntu 24.04（内核 6.8.0-xx）`）。
  final String platform;

  /// 区域与语言（系统区域设置的 BCP-47 标签，如 `zh-CN`）。
  final String locale;

  /// 当前本地日期时间（含时区偏移）。
  final String localTime;

  /// CPU 型号与物理核心数。
  final String cpu;

  /// 内存总量与可用量。
  final String memory;

  /// 局域网 IP 地址列表（地址 + 接口名；无地址时为空表，由界面展示占位）。
  final List<String> ipAddresses;

  const SystemSnapshot({
    required this.platform,
    required this.locale,
    required this.localTime,
    required this.cpu,
    required this.memory,
    required this.ipAddresses,
  });

  @override
  int get hashCode =>
      platform.hashCode ^
      locale.hashCode ^
      localTime.hashCode ^
      cpu.hashCode ^
      memory.hashCode ^
      ipAddresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemSnapshot &&
          runtimeType == other.runtimeType &&
          platform == other.platform &&
          locale == other.locale &&
          localTime == other.localTime &&
          cpu == other.cpu &&
          memory == other.memory &&
          ipAddresses == other.ipAddresses;
}
