// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../sysinfo_view.dart';
import 'init.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 设置（`Some`）或清空（`None`）本机短名；返回刷新后的完整快照。
///
/// 短名不合法时返回可读错误（界面展示），原值保持不变。
Future<AppSnapshot> setShortName({String? name}) =>
    RustLib.instance.api.crateApiDeviceSetShortName(name: name);
