// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../sysinfo_view.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 初始化：解析数据目录、读取/创建配置，返回完整快照。
Future<AppSnapshot> appInit() => RustLib.instance.api.crateApiInitAppInit();

/// 仅刷新系统信息（面板的「刷新」动作；身份与配置不变）。
Future<SystemSnapshot> refreshSystem() =>
    RustLib.instance.api.crateApiInitRefreshSystem();

/// 应用启动快照（信息面板的数据面）。
class AppSnapshot {
  /// 应用版本（新应用版本源）。
  final String version;

  /// 设备 UUID（持久）。
  final String uuid;

  /// 本机默认短名；`None` 表示未设置。
  final String? shortName;

  /// 一次性界面提示（如配置损坏重建）；正常时为 `None`。
  final String? notice;

  /// 系统信息。
  final SystemSnapshot system;

  const AppSnapshot({
    required this.version,
    required this.uuid,
    this.shortName,
    this.notice,
    required this.system,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      uuid.hashCode ^
      shortName.hashCode ^
      notice.hashCode ^
      system.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSnapshot &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          uuid == other.uuid &&
          shortName == other.shortName &&
          notice == other.notice &&
          system == other.system;
}
