// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_state`, `probe_peer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 发现到的设备列表（含已配对与冲突标记）。
Future<List<DiscoveredDeviceInfo>> discoveredDevices() =>
    RustLib.instance.api.crateApiPairDiscoveredDevices();

/// 当前待决配对请求（界面 1 秒轮询）。
Future<PendingPairingInfo?> pairingPending() =>
    RustLib.instance.api.crateApiPairPairingPending();

/// 对当前待决请求做出决定（同意 / 拒绝）。
Future<void> respondPairing({required bool approve}) =>
    RustLib.instance.api.crateApiPairRespondPairing(approve: approve);

/// 向发现到的设备发起配对；同意后自动写入 `[[peer]]`。
Future<PairOutcomeInfo> requestPairing({required String uuid}) =>
    RustLib.instance.api.crateApiPairRequestPairing(uuid: uuid);

/// 已配对设备的在线状态（界面 5 秒轮询）。
Future<List<PeerStatusInfo>> peersStatus() =>
    RustLib.instance.api.crateApiPairPeersStatus();

/// 发现到的设备（界面列表用）。
class DiscoveredDeviceInfo {
  final String uuid;
  final String? shortName;
  final String hostname;
  final int port;

  /// 信标来源 IP（配对写入 address 时采用）。
  final String sourceIp;

  /// 是否已配对（配置中已有同 uuid 条目）。
  final bool paired;

  /// 短名在发现集合内是否冲突（冲突则短名无效）。
  final bool conflicted;

  const DiscoveredDeviceInfo({
    required this.uuid,
    this.shortName,
    required this.hostname,
    required this.port,
    required this.sourceIp,
    required this.paired,
    required this.conflicted,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      shortName.hashCode ^
      hostname.hashCode ^
      port.hashCode ^
      sourceIp.hashCode ^
      paired.hashCode ^
      conflicted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredDeviceInfo &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          shortName == other.shortName &&
          hostname == other.hostname &&
          port == other.port &&
          sourceIp == other.sourceIp &&
          paired == other.paired &&
          conflicted == other.conflicted;
}

/// 发现功能状态（进入启动快照）。
class DiscoverySnapshot {
  /// UDP 信标监听是否可用。
  final bool available;

  /// 可用说明 / 不可用原因。
  final String detail;

  const DiscoverySnapshot({required this.available, required this.detail});

  @override
  int get hashCode => available.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoverySnapshot &&
          runtimeType == other.runtimeType &&
          available == other.available &&
          detail == other.detail;
}

/// 配对结果。
class PairOutcomeInfo {
  /// "paired" | "rejected" | "timeout" | "busy" | "not_found" | "unreachable"
  final String status;
  final String detail;

  const PairOutcomeInfo({required this.status, required this.detail});

  @override
  int get hashCode => status.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairOutcomeInfo &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          detail == other.detail;
}

/// 已配对设备状态。
class PeerStatusInfo {
  final String uuid;
  final String? shortName;
  final String address;
  final int port;

  /// "online" | "unauthorized" | "offline"
  final String status;
  final String note;
  final bool conflicted;

  const PeerStatusInfo({
    required this.uuid,
    this.shortName,
    required this.address,
    required this.port,
    required this.status,
    required this.note,
    required this.conflicted,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      shortName.hashCode ^
      address.hashCode ^
      port.hashCode ^
      status.hashCode ^
      note.hashCode ^
      conflicted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerStatusInfo &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          shortName == other.shortName &&
          address == other.address &&
          port == other.port &&
          status == other.status &&
          note == other.note &&
          conflicted == other.conflicted;
}

/// 待决配对请求（界面弹窗用）。
class PendingPairingInfo {
  final BigInt id;
  final String uuid;
  final String? shortName;
  final int port;
  final String sourceIp;

  const PendingPairingInfo({
    required this.id,
    required this.uuid,
    this.shortName,
    required this.port,
    required this.sourceIp,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      uuid.hashCode ^
      shortName.hashCode ^
      port.hashCode ^
      sourceIp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingPairingInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          uuid == other.uuid &&
          shortName == other.shortName &&
          port == other.port &&
          sourceIp == other.sourceIp;
}
